#!/usr/bin/env bash
# creates a file, displays a string indefinitely, handles SIGTERM, SIGINT, SIGQUIT
touch /var/run/holbertonscript.pid
echo $$ > /var/run/holbertonscript.pid
trap "echo 'I hate the kill command'; rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
