#!/usr/bin/env bash
# prints bad luck when 4 good luck with 8
n=1

while ((n <= 10))
do

    if ((n == 4))
    then
        echo "bad luck"
    elif ((n == 8))
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    n=$((n+1))
done
