#!/usr/bin/env bash
#printing supersticious numbers
n=1
while ((n <= 20))
do
    case $n in
        4)
            echo "bad luck from China"
        ;;
        9)
            echo "bad luck from Japan"
        ;;
        17)
            echo "bad luck from Italy"
        ;;
        *)
        echo "$n"
    esac
    n=$((n+1))
done
