#!/usr/bin/env bash
#printing supersticious numbers
n=1

while ((n <= 20))
do
    echo "$n"
    if ((n == 4))
    then
        echo "bad luck from China"
    elif ((n == 9))
    then
        echo "bad luck from Japan"
    elif ((n == 17))
    then
        echo "bad luck from Italy"
    fi
    n=$((n+1))
done
