#!/usr/bin/env bash
#displays hours from 0 to 12 59
h=0
while [ $h -le 12 ]
do
    m=1
    echo "Hour: $h"
    while [ $m -le 59 ]
    do
        echo "$m"
        m=$((m+1))
    done
    h=$((h+1))
done
