#!/usr/bin/env bash
# Creates a redirection
sudo apt-get -y update
sudo apt-get install -y nginx
command="rewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
dest_file="/etc/nginx/sites-available/default"
sudo sed -i "29s/^/ $(echo -e "\t")$command\n/" $dest_file
sudo service nginx restart
