#!/usr/bin/env bash
# Creates a custom 404 page
sudo apt-get -y update
sudo apt-get install -y nginx
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
command="error_page 404 /404.html;"
dest_file="/etc/nginx/sites-available/default"
sudo sed -i "38i\ $(echo -e "\t")$command" $dest_file
sudo service nginx restart
